### ISSUE TITLE
Suggestion: Allow for mod to be disabled by default

### ISSUE THREAD

**Issue by Hedwig7s** [hschwar/AccurateBlockPlacement-Reborn#2]
A lot of servers have anticheats that block this. Be sick to have it disabled by default and then be able to toggle it on in a singleplayer server (or heck allow toggling based on singleplayer/multiplayer although that's probably more complex)

**Comment by hschwar** [comment]
Maybe default on in singleplayer and default off in multiplayer, but multiplayer gives a warning and needs confirmation.

I'm not sure how that would be done so it might be a while until I get around to this.

**Comment by Hedwig7s** [comment]
There's probably events when connecting to multiplayer or singleplayer (or heck opening the singleplayer or multiplayer menu) which can be used to detect and toggle the setting

**Comment by BeeFox-sys** [comment]
i think just saving the setting between game loads is all that is really needed for this to be closed

**Comment by KadTheHunter** [comment]
I know that the original request was for disabled by default, but I feel that's counterintuitive, and that having defaults for singleplayer/multiplayer is both complicated and ultimately the users responsibility, not the mods.

If simply saving the state of the mod between restarts (as proposed by @BeeFox-sys) is an acceptable solution, I can close this issue, as I've added this feature in an upcoming release. 

Please let me know @Hedwig7s @hschwar.

**Comment by KadTheHunter** [comment]
Going to close this for now, as 011cc4d9ac4f8422a8dc3a128728a7f61b5f5560 / [v1.3.0](https://github.com/hschwar/AccurateBlockPlacement-Reborn/releases/tag/1.3.0) adds Cloth Config.

To reiterate my reasoning from above:
Enabling/Disabling the mods features is the users responsibility. In order to make it easier to do so (and to remember their choices between restarts), Cloth Config has been added.

Default states for Singleplayer/Multiplayer *could* still be added, but I personally disagree with it.
